// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://api.wavetrophy.d4rkmindz.ch/v1',
  baseUrl: 'https://api.wavetrophy.d4rkmindz.ch',
  defaultLanguage: 'de-CH',
  supportedLanguages: [
    'en-US',
    'de-CH'
  ],
  keys: {
    credentials: 'credentials',
  }
};
